# Generated by Django 4.2.1 on 2023-06-06 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='idcellars',
        ),
        migrations.RemoveField(
            model_name='historicalclient',
            name='idcellars',
        ),
    ]
