# Generated by Django 4.2.1 on 2023-06-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_client_idcellars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='iddestinations',
            field=models.IntegerField(blank=True, db_column='IdDestinations', null=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='iddestinations',
            field=models.IntegerField(blank=True, db_column='IdDestinations', null=True),
        ),
    ]
