# Generated by Django 4.2.1 on 2023-06-06 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
        ('client', '0003_client_iddestinations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='iddestinations',
            field=models.ForeignKey(db_column='IdDestinations', on_delete=django.db.models.deletion.CASCADE, to='routes.destinations'),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='iddestinations',
            field=models.ForeignKey(blank=True, db_column='IdDestinations', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='routes.destinations'),
        ),
    ]
