# Generated by Django 4.2.1 on 2023-06-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_remove_guide_idcellars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='idlocation',
            field=models.IntegerField(blank=True, db_column='IdLocation', null=True),
        ),
        migrations.AddField(
            model_name='historicalguide',
            name='idlocation',
            field=models.IntegerField(blank=True, db_column='IdLocation', null=True),
        ),
    ]
