# Generated by Django 4.2.1 on 2023-06-22 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_historicallocality_latitude_and_more'),
        ('guide', '0003_guide_idlocation_historicalguide_idlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='idlocation',
            field=models.ForeignKey(db_column='IdLocation', on_delete=django.db.models.deletion.CASCADE, to='company.locality'),
        ),
        migrations.AlterField(
            model_name='historicalguide',
            name='idlocation',
            field=models.ForeignKey(blank=True, db_column='IdLocation', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.locality'),
        ),
    ]
