# Generated by Django 4.2.1 on 2023-07-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0005_travel_historicaltravel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltravel',
            name='tank',
            field=models.DecimalField(blank=True, db_column='Tank', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='tank',
            field=models.DecimalField(blank=True, db_column='Tank', decimal_places=2, max_digits=10, null=True),
        ),
    ]
