# Generated by Django 4.2.1 on 2023-07-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0006_alter_historicaltravel_tank_alter_travel_tank'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='idvehicle',
            field=models.IntegerField(blank=True, db_column='IdVehicle', null=True),
        ),
        migrations.AddField(
            model_name='historicalguide',
            name='idvehicle',
            field=models.IntegerField(blank=True, db_column='IdVehicle', null=True),
        ),
    ]
