# Generated by Django 4.2.1 on 2023-07-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0008_alter_guide_idvehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='finalized',
            field=models.BooleanField(db_column='Finalized', default=False),
        ),
        migrations.AddField(
            model_name='guide',
            name='initialized',
            field=models.BooleanField(db_column='initialized', default=False),
        ),
        migrations.AddField(
            model_name='guide',
            name='route',
            field=models.BooleanField(db_column='Route', default=False),
        ),
        migrations.AddField(
            model_name='historicalguide',
            name='finalized',
            field=models.BooleanField(db_column='Finalized', default=False),
        ),
        migrations.AddField(
            model_name='historicalguide',
            name='initialized',
            field=models.BooleanField(db_column='initialized', default=False),
        ),
        migrations.AddField(
            model_name='historicalguide',
            name='route',
            field=models.BooleanField(db_column='Route', default=False),
        ),
        migrations.AlterField(
            model_name='guide',
            name='status',
            field=models.BooleanField(db_column='State', default=False),
        ),
        migrations.AlterField(
            model_name='historicalguide',
            name='status',
            field=models.BooleanField(db_column='State', default=False),
        ),
    ]
