# Generated by Django 4.2.1 on 2023-07-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0009_guide_finalized_guide_initialized_guide_route_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltravel',
            name='kml',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='kml',
        ),
        migrations.AddField(
            model_name='historicaltravel',
            name='kms',
            field=models.DecimalField(blank=True, db_column='Kms', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='kms',
            field=models.DecimalField(blank=True, db_column='Kms', decimal_places=2, max_digits=10, null=True),
        ),
    ]
