# Generated by Django 4.2.1 on 2023-07-21 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guide', '0010_remove_historicaltravel_kml_remove_travel_kml_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideContent',
            fields=[
                ('idguidecontent', models.AutoField(db_column='IdGuideContent', primary_key=True, serialize=False)),
                ('authorizacionno', models.CharField(db_column='AuthorizacionNo', max_length=7)),
                ('receiptno', models.CharField(db_column='ReceiptNo', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceType',
            fields=[
                ('idinvoicetype', models.AutoField(db_column='IdInvoiceType', primary_key=True, serialize=False)),
                ('invoicetype', models.CharField(db_column='InvoiceType', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Unity',
            fields=[
                ('idunity', models.AutoField(db_column='IdUnity', primary_key=True, serialize=False)),
                ('unity', models.CharField(db_column='Unity', max_length=5)),
            ],
        ),
        migrations.RenameField(
            model_name='guide',
            old_name='idGuide',
            new_name='idguide',
        ),
        migrations.RenameField(
            model_name='historicalguide',
            old_name='idGuide',
            new_name='idguide',
        ),
        migrations.CreateModel(
            name='HistoricalUnity',
            fields=[
                ('idunity', models.IntegerField(blank=True, db_column='IdUnity', db_index=True)),
                ('unity', models.CharField(db_column='Unity', max_length=5)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical unity',
                'verbose_name_plural': 'historical unitys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalInvoiceType',
            fields=[
                ('idinvoicetype', models.IntegerField(blank=True, db_column='IdInvoiceType', db_index=True)),
                ('invoicetype', models.CharField(db_column='InvoiceType', max_length=5)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical invoice type',
                'verbose_name_plural': 'historical invoice types',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalGuideContentDetailTmp',
            fields=[
                ('idguidecontentdetailtpm', models.IntegerField(blank=True, db_column='IdGuideContentDetailTmp', db_index=True)),
                ('description', models.CharField(db_column='Description', max_length=7)),
                ('amount', models.IntegerField(db_column='Amount')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('idemployee', models.ForeignKey(blank=True, db_column='IdEmployee', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.employee')),
                ('idguide', models.ForeignKey(blank=True, db_column='IdGuide', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='guide.guide')),
                ('idunit', models.ForeignKey(blank=True, db_column='IdUnit', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='guide.unity')),
            ],
            options={
                'verbose_name': 'historical guide content detail tmp',
                'verbose_name_plural': 'historical guide content detail tmps',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalGuideContentDetail',
            fields=[
                ('idguidecontentdetail', models.IntegerField(blank=True, db_column='IdGuideContentDetail', db_index=True)),
                ('description', models.CharField(db_column='Description', max_length=7)),
                ('amount', models.IntegerField(db_column='Amount')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('idguidecontent', models.ForeignKey(blank=True, db_column='IdGuideContent', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='guide.guidecontent')),
                ('idunit', models.ForeignKey(blank=True, db_column='IdUnit', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='guide.unity')),
            ],
            options={
                'verbose_name': 'historical guide content detail',
                'verbose_name_plural': 'historical guide content details',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalGuideContent',
            fields=[
                ('idguidecontent', models.IntegerField(blank=True, db_column='IdGuideContent', db_index=True)),
                ('authorizacionno', models.CharField(db_column='AuthorizacionNo', max_length=7)),
                ('receiptno', models.CharField(db_column='ReceiptNo', max_length=7)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('idguide', models.ForeignKey(blank=True, db_column='IdGuide', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='guide.guide')),
                ('idinvoicetype', models.ForeignKey(blank=True, db_column='IdInvoiceType', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='guide.invoicetype')),
            ],
            options={
                'verbose_name': 'historical guide content',
                'verbose_name_plural': 'historical guide contents',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='GuideContentDetailTmp',
            fields=[
                ('idguidecontentdetailtpm', models.AutoField(db_column='IdGuideContentDetailTmp', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='Description', max_length=7)),
                ('amount', models.IntegerField(db_column='Amount')),
                ('idemployee', models.ForeignKey(db_column='IdEmployee', on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('idguide', models.ForeignKey(db_column='IdGuide', on_delete=django.db.models.deletion.CASCADE, to='guide.guide')),
                ('idunit', models.ForeignKey(db_column='IdUnit', on_delete=django.db.models.deletion.CASCADE, to='guide.unity')),
            ],
        ),
        migrations.CreateModel(
            name='GuideContentDetail',
            fields=[
                ('idguidecontentdetail', models.AutoField(db_column='IdGuideContentDetail', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='Description', max_length=7)),
                ('amount', models.IntegerField(db_column='Amount')),
                ('idguidecontent', models.ForeignKey(db_column='IdGuideContent', on_delete=django.db.models.deletion.CASCADE, to='guide.guidecontent')),
                ('idunit', models.ForeignKey(db_column='IdUnit', on_delete=django.db.models.deletion.CASCADE, to='guide.unity')),
            ],
        ),
        migrations.AddField(
            model_name='guidecontent',
            name='idguide',
            field=models.ForeignKey(db_column='IdGuide', on_delete=django.db.models.deletion.CASCADE, to='guide.guide'),
        ),
        migrations.AddField(
            model_name='guidecontent',
            name='idinvoicetype',
            field=models.ForeignKey(db_column='IdInvoiceType', on_delete=django.db.models.deletion.CASCADE, to='guide.invoicetype'),
        ),
    ]
