# Generated by Django 4.2.1 on 2023-07-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0011_guidecontent_invoicetype_unity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidecontent',
            name='customsdeclarationnumber',
            field=models.CharField(blank=True, db_column='CustomsDeclarationNumber', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='guidecontent',
            name='reasonfortransfer',
            field=models.CharField(blank=True, db_column='ReasonForTransfer', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='historicalguidecontent',
            name='customsdeclarationnumber',
            field=models.CharField(blank=True, db_column='CustomsDeclarationNumber', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='historicalguidecontent',
            name='reasonfortransfer',
            field=models.CharField(blank=True, db_column='ReasonForTransfer', max_length=7, null=True),
        ),
    ]
