# Generated by Django 4.2.1 on 2023-07-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0014_alter_historicalinvoicetype_invoicetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidecontent',
            name='authorizacionno',
            field=models.CharField(db_column='AuthorizacionNo', max_length=225),
        ),
        migrations.AlterField(
            model_name='guidecontent',
            name='customsdeclarationnumber',
            field=models.CharField(blank=True, db_column='CustomsDeclarationNumber', max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='guidecontent',
            name='reasonfortransfer',
            field=models.CharField(blank=True, db_column='ReasonForTransfer', max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='guidecontent',
            name='receiptno',
            field=models.CharField(db_column='ReceiptNo', max_length=225),
        ),
        migrations.AlterField(
            model_name='guidecontentdetail',
            name='description',
            field=models.CharField(db_column='Description', max_length=225),
        ),
        migrations.AlterField(
            model_name='guidecontentdetailtmp',
            name='description',
            field=models.CharField(db_column='Description', max_length=225),
        ),
        migrations.AlterField(
            model_name='historicalguidecontent',
            name='authorizacionno',
            field=models.CharField(db_column='AuthorizacionNo', max_length=225),
        ),
        migrations.AlterField(
            model_name='historicalguidecontent',
            name='customsdeclarationnumber',
            field=models.CharField(blank=True, db_column='CustomsDeclarationNumber', max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='historicalguidecontent',
            name='reasonfortransfer',
            field=models.CharField(blank=True, db_column='ReasonForTransfer', max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='historicalguidecontent',
            name='receiptno',
            field=models.CharField(db_column='ReceiptNo', max_length=225),
        ),
        migrations.AlterField(
            model_name='historicalguidecontentdetail',
            name='description',
            field=models.CharField(db_column='Description', max_length=225),
        ),
        migrations.AlterField(
            model_name='historicalguidecontentdetailtmp',
            name='description',
            field=models.CharField(db_column='Description', max_length=225),
        ),
    ]
