# Generated by Django 4.2.1 on 2023-06-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaldata',
            name='ntravelkmmonth',
            field=models.DecimalField(db_column='NtravelKmMonth', decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalgeneraldata',
            name='ntravelkmmonth',
            field=models.DecimalField(db_column='NtravelKmMonth', decimal_places=2, max_digits=10),
        ),
    ]
