# Generated by Django 4.2.1 on 2023-06-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_alter_generaldata_ntravelkmmonth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='acCkm',
            field=models.DecimalField(blank=True, db_column='AcCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='acCu',
            field=models.DecimalField(blank=True, db_column='AcCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='acDkm',
            field=models.DecimalField(blank=True, db_column='AcDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='acQ',
            field=models.DecimalField(blank=True, db_column='AcQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='accessoriesCkm',
            field=models.DecimalField(blank=True, db_column='AccessoriesCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='accessoriesCu',
            field=models.DecimalField(blank=True, db_column='AccessoriesCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='accessoriesDkm',
            field=models.DecimalField(blank=True, db_column='AccessoriesDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='accessoriesQ',
            field=models.DecimalField(blank=True, db_column='AccessoriesQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='addressCkm',
            field=models.DecimalField(blank=True, db_column='AddressCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='addressCu',
            field=models.DecimalField(blank=True, db_column='AddressCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='addressDkm',
            field=models.DecimalField(blank=True, db_column='AddressDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='addressQ',
            field=models.DecimalField(blank=True, db_column='AddressQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='adjustmentscalibrationsCkm',
            field=models.DecimalField(blank=True, db_column='AdjustmentscalibrationsCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='adjustmentscalibrationsCu',
            field=models.DecimalField(blank=True, db_column='AdjustmentscalibrationsCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='adjustmentscalibrationsDkm',
            field=models.DecimalField(blank=True, db_column='AdjustmentscalibrationsDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='adjustmentscalibrationsQ',
            field=models.DecimalField(blank=True, db_column='AdjustmentscalibrationsQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='airfiltersCkm',
            field=models.DecimalField(blank=True, db_column='AirfiltersCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='airfiltersCu',
            field=models.DecimalField(blank=True, db_column='AirfiltersCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='airfiltersDkm',
            field=models.DecimalField(blank=True, db_column='AirfiltersDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='airfiltersQ',
            field=models.DecimalField(blank=True, db_column='AirfiltersQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='airpurifierCkm',
            field=models.DecimalField(blank=True, db_column='AirpurifierCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='airpurifierCu',
            field=models.DecimalField(blank=True, db_column='AirpurifierCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='airpurifierDkm',
            field=models.DecimalField(blank=True, db_column='AirpurifierDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='airpurifierQ',
            field=models.DecimalField(blank=True, db_column='AirpurifierQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='alignmentCkm',
            field=models.DecimalField(blank=True, db_column='AlignmentCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='alignmentCu',
            field=models.DecimalField(blank=True, db_column='AlignmentCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='alignmentDkm',
            field=models.DecimalField(blank=True, db_column='AlignmentDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='alignmentQ',
            field=models.DecimalField(blank=True, db_column='AlignmentQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='alternatorCkm',
            field=models.DecimalField(blank=True, db_column='AlternatorCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='alternatorCu',
            field=models.DecimalField(blank=True, db_column='AlternatorCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='alternatorDkm',
            field=models.DecimalField(blank=True, db_column='AlternatorDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='alternatorQ',
            field=models.DecimalField(blank=True, db_column='AlternatorQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='batteriesCkm',
            field=models.DecimalField(blank=True, db_column='BatteriesCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='batteriesCu',
            field=models.DecimalField(blank=True, db_column='BatteriesCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='batteriesDkm',
            field=models.DecimalField(blank=True, db_column='BatteriesDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='batteriesQ',
            field=models.DecimalField(blank=True, db_column='BatteriesQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='boxCkm',
            field=models.DecimalField(blank=True, db_column='BoxCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='boxCu',
            field=models.DecimalField(blank=True, db_column='BoxCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='boxDkm',
            field=models.DecimalField(blank=True, db_column='BoxDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='boxQ',
            field=models.DecimalField(blank=True, db_column='BoxQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='cardanCkm',
            field=models.DecimalField(blank=True, db_column='CardanCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='cardanCu',
            field=models.DecimalField(blank=True, db_column='CardanCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='cardanDkm',
            field=models.DecimalField(blank=True, db_column='CardanDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='cardanQ',
            field=models.DecimalField(blank=True, db_column='CardanQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='casetransmissionoilCkm',
            field=models.DecimalField(blank=True, db_column='CasetransmissionoilCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='casetransmissionoilCu',
            field=models.DecimalField(blank=True, db_column='CasetransmissionoilCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='casetransmissionoilDkm',
            field=models.DecimalField(blank=True, db_column='CasetransmissionoilDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='casetransmissionoilQ',
            field=models.DecimalField(blank=True, db_column='CasetransmissionoilQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='cleaningCkm',
            field=models.DecimalField(blank=True, db_column='CleaningCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='cleaningCu',
            field=models.DecimalField(blank=True, db_column='CleaningCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='cleaningDkm',
            field=models.DecimalField(blank=True, db_column='CleaningDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='cleaningQ',
            field=models.DecimalField(blank=True, db_column='CleaningQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='clutchclutchCkm',
            field=models.DecimalField(blank=True, db_column='ClutchclutchCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='clutchclutchCu',
            field=models.DecimalField(blank=True, db_column='ClutchclutchCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='clutchclutchDkm',
            field=models.DecimalField(blank=True, db_column='ClutchclutchDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='clutchclutchQ',
            field=models.DecimalField(blank=True, db_column='ClutchclutchQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='coolingCkm',
            field=models.DecimalField(blank=True, db_column='CoolingCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='coolingCu',
            field=models.DecimalField(blank=True, db_column='CoolingCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='coolingDkm',
            field=models.DecimalField(blank=True, db_column='CoolingDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='coolingQ',
            field=models.DecimalField(blank=True, db_column='CoolingQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='dragtiresCkm',
            field=models.DecimalField(blank=True, db_column='DragtiresCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='dragtiresCu',
            field=models.DecimalField(blank=True, db_column='DragtiresCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='dragtiresDkm',
            field=models.DecimalField(blank=True, db_column='DragtiresDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='dragtiresQ',
            field=models.DecimalField(blank=True, db_column='DragtiresQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='drivetiresCkm',
            field=models.DecimalField(blank=True, db_column='DrivetiresCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='drivetiresCu',
            field=models.DecimalField(blank=True, db_column='DrivetiresCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='drivetiresDkm',
            field=models.DecimalField(blank=True, db_column='DrivetiresDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='drivetiresQ',
            field=models.DecimalField(blank=True, db_column='DrivetiresQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='drumsCkm',
            field=models.DecimalField(blank=True, db_column='DrumsCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='drumsCu',
            field=models.DecimalField(blank=True, db_column='DrumsCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='drumsDkm',
            field=models.DecimalField(blank=True, db_column='DrumsDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='drumsQ',
            field=models.DecimalField(blank=True, db_column='DrumsQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='electronicsystemCkm',
            field=models.DecimalField(blank=True, db_column='ElectronicsystemCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='electronicsystemCu',
            field=models.DecimalField(blank=True, db_column='ElectronicsystemCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='electronicsystemDkm',
            field=models.DecimalField(blank=True, db_column='ElectronicsystemDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='electronicsystemQ',
            field=models.DecimalField(blank=True, db_column='ElectronicsystemQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='engineoverhaulCkm',
            field=models.DecimalField(blank=True, db_column='EngineoverhaulCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='engineoverhaulCu',
            field=models.DecimalField(blank=True, db_column='EngineoverhaulCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='engineoverhaulDkm',
            field=models.DecimalField(blank=True, db_column='EngineoverhaulDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='engineoverhaulQ',
            field=models.DecimalField(blank=True, db_column='EngineoverhaulQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='exhaustsystemCkm',
            field=models.DecimalField(blank=True, db_column='ExhaustsystemCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='exhaustsystemCu',
            field=models.DecimalField(blank=True, db_column='ExhaustsystemCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='exhaustsystemDkm',
            field=models.DecimalField(blank=True, db_column='ExhaustsystemDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='exhaustsystemQ',
            field=models.DecimalField(blank=True, db_column='ExhaustsystemQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='frontloadaxleCkm',
            field=models.DecimalField(blank=True, db_column='FrontloadaxleCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='frontloadaxleCu',
            field=models.DecimalField(blank=True, db_column='FrontloadaxleCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='frontloadaxleDkm',
            field=models.DecimalField(blank=True, db_column='FrontloadaxleDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='frontloadaxleQ',
            field=models.DecimalField(blank=True, db_column='FrontloadaxleQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='fronttiresCkm',
            field=models.DecimalField(blank=True, db_column='FronttiresCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='fronttiresCu',
            field=models.DecimalField(blank=True, db_column='FronttiresCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='fronttiresDkm',
            field=models.DecimalField(blank=True, db_column='FronttiresDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='fronttiresQ',
            field=models.DecimalField(blank=True, db_column='FronttiresQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='fuelpumpCkm',
            field=models.DecimalField(blank=True, db_column='FuelpumpCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='fuelpumpCu',
            field=models.DecimalField(blank=True, db_column='FuelpumpCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='fuelpumpDkm',
            field=models.DecimalField(blank=True, db_column='FuelpumpDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='fuelpumpQ',
            field=models.DecimalField(blank=True, db_column='FuelpumpQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='glassesandcleaningsystemCkm',
            field=models.DecimalField(blank=True, db_column='GlassesandcleaningsystemCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='glassesandcleaningsystemCu',
            field=models.DecimalField(blank=True, db_column='GlassesandcleaningsystemCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='glassesandcleaningsystemDkm',
            field=models.DecimalField(blank=True, db_column='GlassesandcleaningsystemDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='glassesandcleaningsystemQ',
            field=models.DecimalField(blank=True, db_column='GlassesandcleaningsystemQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='intonationtuningCkm',
            field=models.DecimalField(blank=True, db_column='IntonationtuningCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='intonationtuningCu',
            field=models.DecimalField(blank=True, db_column='IntonationtuningCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='intonationtuningDkm',
            field=models.DecimalField(blank=True, db_column='IntonationtuningDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='intonationtuningQ',
            field=models.DecimalField(blank=True, db_column='IntonationtuningQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='lightsCkm',
            field=models.DecimalField(blank=True, db_column='LightsCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='lightsCu',
            field=models.DecimalField(blank=True, db_column='LightsCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='lightsDkm',
            field=models.DecimalField(blank=True, db_column='LightsDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='lightsQ',
            field=models.DecimalField(blank=True, db_column='LightsQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='lubricantsfluidsCkm',
            field=models.DecimalField(blank=True, db_column='LubricantsfluidsCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='lubricantsfluidsCu',
            field=models.DecimalField(blank=True, db_column='LubricantsfluidsCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='lubricantsfluidsDkm',
            field=models.DecimalField(blank=True, db_column='LubricantsfluidsDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='lubricantsfluidsQ',
            field=models.DecimalField(blank=True, db_column='LubricantsfluidsQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='majorrepairCkm',
            field=models.DecimalField(blank=True, db_column='MajorrepairCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='majorrepairCu',
            field=models.DecimalField(blank=True, db_column='MajorrepairCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='majorrepairDkm',
            field=models.DecimalField(blank=True, db_column='MajorrepairDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='majorrepairQ',
            field=models.DecimalField(blank=True, db_column='MajorrepairQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='minorrepairCkm',
            field=models.DecimalField(blank=True, db_column='MinorrepairCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='minorrepairCu',
            field=models.DecimalField(blank=True, db_column='MinorrepairCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='minorrepairDkm',
            field=models.DecimalField(blank=True, db_column='MinorrepairDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='minorrepairQ',
            field=models.DecimalField(blank=True, db_column='MinorrepairQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='oilchangeCkm',
            field=models.DecimalField(blank=True, db_column='OilchangeCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='oilchangeCu',
            field=models.DecimalField(blank=True, db_column='OilchangeCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='oilchangeDkm',
            field=models.DecimalField(blank=True, db_column='OilchangeDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='oilchangeQ',
            field=models.DecimalField(blank=True, db_column='OilchangeQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='oilsystemCkm',
            field=models.DecimalField(blank=True, db_column='OilsystemCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='oilsystemCu',
            field=models.DecimalField(blank=True, db_column='OilsystemCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='oilsystemDkm',
            field=models.DecimalField(blank=True, db_column='OilsystemDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='oilsystemQ',
            field=models.DecimalField(blank=True, db_column='OilsystemQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='pinCkm',
            field=models.DecimalField(blank=True, db_column='PinCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='pinCu',
            field=models.DecimalField(blank=True, db_column='PinCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='pinDkm',
            field=models.DecimalField(blank=True, db_column='PinDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='pinQ',
            field=models.DecimalField(blank=True, db_column='PinQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='pressuregaugesCkm',
            field=models.DecimalField(blank=True, db_column='PressuregaugesCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='pressuregaugesCu',
            field=models.DecimalField(blank=True, db_column='PressuregaugesCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='pressuregaugesDkm',
            field=models.DecimalField(blank=True, db_column='PressuregaugesDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='pressuregaugesQ',
            field=models.DecimalField(blank=True, db_column='PressuregaugesQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='puncturesanddamageCkm',
            field=models.DecimalField(blank=True, db_column='PuncturesanddamageCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='puncturesanddamageCu',
            field=models.DecimalField(blank=True, db_column='PuncturesanddamageCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='puncturesanddamageDkm',
            field=models.DecimalField(blank=True, db_column='PuncturesanddamageDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='puncturesanddamageQ',
            field=models.DecimalField(blank=True, db_column='PuncturesanddamageQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='radiatorCkm',
            field=models.DecimalField(blank=True, db_column='RadiatorCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='radiatorCu',
            field=models.DecimalField(blank=True, db_column='RadiatorCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='radiatorDkm',
            field=models.DecimalField(blank=True, db_column='RadiatorDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='radiatorQ',
            field=models.DecimalField(blank=True, db_column='RadiatorQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='rearloadaxleCkm',
            field=models.DecimalField(blank=True, db_column='RearloadaxleCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='rearloadaxleCu',
            field=models.DecimalField(blank=True, db_column='RearloadaxleCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='rearloadaxleDkm',
            field=models.DecimalField(blank=True, db_column='RearloadaxleDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='rearloadaxleQ',
            field=models.DecimalField(blank=True, db_column='RearloadaxleQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='rubberCkm',
            field=models.DecimalField(blank=True, db_column='RubberCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='rubberCu',
            field=models.DecimalField(blank=True, db_column='RubberCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='rubberDkm',
            field=models.DecimalField(blank=True, db_column='RubberDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='rubberQ',
            field=models.DecimalField(blank=True, db_column='RubberQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='sealsCkm',
            field=models.DecimalField(blank=True, db_column='SealsCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='sealsCu',
            field=models.DecimalField(blank=True, db_column='SealsCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='sealsDkm',
            field=models.DecimalField(blank=True, db_column='SealsDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='sealsQ',
            field=models.DecimalField(blank=True, db_column='SealsQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='springsleafspringsCkm',
            field=models.DecimalField(blank=True, db_column='SpringsleafspringsCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='springsleafspringsCu',
            field=models.DecimalField(blank=True, db_column='SpringsleafspringsCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='springsleafspringsDkm',
            field=models.DecimalField(blank=True, db_column='SpringsleafspringsDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='springsleafspringsQ',
            field=models.DecimalField(blank=True, db_column='SpringsleafspringsQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='startingmotorCkm',
            field=models.DecimalField(blank=True, db_column='StartingmotorCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='startingmotorCu',
            field=models.DecimalField(blank=True, db_column='StartingmotorCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='startingmotorDkm',
            field=models.DecimalField(blank=True, db_column='StartingmotorDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='startingmotorQ',
            field=models.DecimalField(blank=True, db_column='StartingmotorQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='swingingCkm',
            field=models.DecimalField(blank=True, db_column='SwingingCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='swingingCu',
            field=models.DecimalField(blank=True, db_column='SwingingCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='swingingDkm',
            field=models.DecimalField(blank=True, db_column='SwingingDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='swingingQ',
            field=models.DecimalField(blank=True, db_column='SwingingQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='total',
            field=models.DecimalField(blank=True, db_column='Total', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='transmissiondifferentialCkm',
            field=models.DecimalField(blank=True, db_column='TransmissiondifferentialCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='transmissiondifferentialCu',
            field=models.DecimalField(blank=True, db_column='TransmissiondifferentialCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='transmissiondifferentialDkm',
            field=models.DecimalField(blank=True, db_column='TransmissiondifferentialDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='transmissiondifferentialQ',
            field=models.DecimalField(blank=True, db_column='TransmissiondifferentialQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='turboCkm',
            field=models.DecimalField(blank=True, db_column='TurboCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='turboCu',
            field=models.DecimalField(blank=True, db_column='TurboCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='turboDkm',
            field=models.DecimalField(blank=True, db_column='TurboDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='turboQ',
            field=models.DecimalField(blank=True, db_column='TurboQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='waterpumpCkm',
            field=models.DecimalField(blank=True, db_column='WaterpumpCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='waterpumpCu',
            field=models.DecimalField(blank=True, db_column='WaterpumpCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='waterpumpDkm',
            field=models.DecimalField(blank=True, db_column='WaterpumpDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='waterpumpQ',
            field=models.DecimalField(blank=True, db_column='WaterpumpQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='wheelsCkm',
            field=models.DecimalField(blank=True, db_column='WheelsCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='wheelsCu',
            field=models.DecimalField(blank=True, db_column='WheelsCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='wheelsDkm',
            field=models.DecimalField(blank=True, db_column='WheelsDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaintenamcecosts',
            name='wheelsQ',
            field=models.DecimalField(blank=True, db_column='WheelsQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='acCkm',
            field=models.DecimalField(blank=True, db_column='AcCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='acCu',
            field=models.DecimalField(blank=True, db_column='AcCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='acDkm',
            field=models.DecimalField(blank=True, db_column='AcDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='acQ',
            field=models.DecimalField(blank=True, db_column='AcQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='accessoriesCkm',
            field=models.DecimalField(blank=True, db_column='AccessoriesCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='accessoriesCu',
            field=models.DecimalField(blank=True, db_column='AccessoriesCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='accessoriesDkm',
            field=models.DecimalField(blank=True, db_column='AccessoriesDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='accessoriesQ',
            field=models.DecimalField(blank=True, db_column='AccessoriesQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='addressCkm',
            field=models.DecimalField(blank=True, db_column='AddressCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='addressCu',
            field=models.DecimalField(blank=True, db_column='AddressCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='addressDkm',
            field=models.DecimalField(blank=True, db_column='AddressDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='addressQ',
            field=models.DecimalField(blank=True, db_column='AddressQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='adjustmentscalibrationsCkm',
            field=models.DecimalField(blank=True, db_column='AdjustmentscalibrationsCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='adjustmentscalibrationsCu',
            field=models.DecimalField(blank=True, db_column='AdjustmentscalibrationsCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='adjustmentscalibrationsDkm',
            field=models.DecimalField(blank=True, db_column='AdjustmentscalibrationsDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='adjustmentscalibrationsQ',
            field=models.DecimalField(blank=True, db_column='AdjustmentscalibrationsQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='airfiltersCkm',
            field=models.DecimalField(blank=True, db_column='AirfiltersCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='airfiltersCu',
            field=models.DecimalField(blank=True, db_column='AirfiltersCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='airfiltersDkm',
            field=models.DecimalField(blank=True, db_column='AirfiltersDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='airfiltersQ',
            field=models.DecimalField(blank=True, db_column='AirfiltersQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='airpurifierCkm',
            field=models.DecimalField(blank=True, db_column='AirpurifierCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='airpurifierCu',
            field=models.DecimalField(blank=True, db_column='AirpurifierCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='airpurifierDkm',
            field=models.DecimalField(blank=True, db_column='AirpurifierDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='airpurifierQ',
            field=models.DecimalField(blank=True, db_column='AirpurifierQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='alignmentCkm',
            field=models.DecimalField(blank=True, db_column='AlignmentCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='alignmentCu',
            field=models.DecimalField(blank=True, db_column='AlignmentCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='alignmentDkm',
            field=models.DecimalField(blank=True, db_column='AlignmentDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='alignmentQ',
            field=models.DecimalField(blank=True, db_column='AlignmentQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='alternatorCkm',
            field=models.DecimalField(blank=True, db_column='AlternatorCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='alternatorCu',
            field=models.DecimalField(blank=True, db_column='AlternatorCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='alternatorDkm',
            field=models.DecimalField(blank=True, db_column='AlternatorDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='alternatorQ',
            field=models.DecimalField(blank=True, db_column='AlternatorQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='batteriesCkm',
            field=models.DecimalField(blank=True, db_column='BatteriesCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='batteriesCu',
            field=models.DecimalField(blank=True, db_column='BatteriesCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='batteriesDkm',
            field=models.DecimalField(blank=True, db_column='BatteriesDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='batteriesQ',
            field=models.DecimalField(blank=True, db_column='BatteriesQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='boxCkm',
            field=models.DecimalField(blank=True, db_column='BoxCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='boxCu',
            field=models.DecimalField(blank=True, db_column='BoxCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='boxDkm',
            field=models.DecimalField(blank=True, db_column='BoxDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='boxQ',
            field=models.DecimalField(blank=True, db_column='BoxQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='cardanCkm',
            field=models.DecimalField(blank=True, db_column='CardanCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='cardanCu',
            field=models.DecimalField(blank=True, db_column='CardanCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='cardanDkm',
            field=models.DecimalField(blank=True, db_column='CardanDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='cardanQ',
            field=models.DecimalField(blank=True, db_column='CardanQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='casetransmissionoilCkm',
            field=models.DecimalField(blank=True, db_column='CasetransmissionoilCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='casetransmissionoilCu',
            field=models.DecimalField(blank=True, db_column='CasetransmissionoilCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='casetransmissionoilDkm',
            field=models.DecimalField(blank=True, db_column='CasetransmissionoilDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='casetransmissionoilQ',
            field=models.DecimalField(blank=True, db_column='CasetransmissionoilQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='cleaningCkm',
            field=models.DecimalField(blank=True, db_column='CleaningCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='cleaningCu',
            field=models.DecimalField(blank=True, db_column='CleaningCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='cleaningDkm',
            field=models.DecimalField(blank=True, db_column='CleaningDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='cleaningQ',
            field=models.DecimalField(blank=True, db_column='CleaningQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='clutchclutchCkm',
            field=models.DecimalField(blank=True, db_column='ClutchclutchCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='clutchclutchCu',
            field=models.DecimalField(blank=True, db_column='ClutchclutchCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='clutchclutchDkm',
            field=models.DecimalField(blank=True, db_column='ClutchclutchDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='clutchclutchQ',
            field=models.DecimalField(blank=True, db_column='ClutchclutchQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='coolingCkm',
            field=models.DecimalField(blank=True, db_column='CoolingCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='coolingCu',
            field=models.DecimalField(blank=True, db_column='CoolingCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='coolingDkm',
            field=models.DecimalField(blank=True, db_column='CoolingDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='coolingQ',
            field=models.DecimalField(blank=True, db_column='CoolingQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='dragtiresCkm',
            field=models.DecimalField(blank=True, db_column='DragtiresCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='dragtiresCu',
            field=models.DecimalField(blank=True, db_column='DragtiresCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='dragtiresDkm',
            field=models.DecimalField(blank=True, db_column='DragtiresDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='dragtiresQ',
            field=models.DecimalField(blank=True, db_column='DragtiresQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='drivetiresCkm',
            field=models.DecimalField(blank=True, db_column='DrivetiresCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='drivetiresCu',
            field=models.DecimalField(blank=True, db_column='DrivetiresCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='drivetiresDkm',
            field=models.DecimalField(blank=True, db_column='DrivetiresDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='drivetiresQ',
            field=models.DecimalField(blank=True, db_column='DrivetiresQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='drumsCkm',
            field=models.DecimalField(blank=True, db_column='DrumsCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='drumsCu',
            field=models.DecimalField(blank=True, db_column='DrumsCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='drumsDkm',
            field=models.DecimalField(blank=True, db_column='DrumsDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='drumsQ',
            field=models.DecimalField(blank=True, db_column='DrumsQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='electronicsystemCkm',
            field=models.DecimalField(blank=True, db_column='ElectronicsystemCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='electronicsystemCu',
            field=models.DecimalField(blank=True, db_column='ElectronicsystemCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='electronicsystemDkm',
            field=models.DecimalField(blank=True, db_column='ElectronicsystemDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='electronicsystemQ',
            field=models.DecimalField(blank=True, db_column='ElectronicsystemQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='engineoverhaulCkm',
            field=models.DecimalField(blank=True, db_column='EngineoverhaulCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='engineoverhaulCu',
            field=models.DecimalField(blank=True, db_column='EngineoverhaulCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='engineoverhaulDkm',
            field=models.DecimalField(blank=True, db_column='EngineoverhaulDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='engineoverhaulQ',
            field=models.DecimalField(blank=True, db_column='EngineoverhaulQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='exhaustsystemCkm',
            field=models.DecimalField(blank=True, db_column='ExhaustsystemCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='exhaustsystemCu',
            field=models.DecimalField(blank=True, db_column='ExhaustsystemCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='exhaustsystemDkm',
            field=models.DecimalField(blank=True, db_column='ExhaustsystemDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='exhaustsystemQ',
            field=models.DecimalField(blank=True, db_column='ExhaustsystemQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='frontloadaxleCkm',
            field=models.DecimalField(blank=True, db_column='FrontloadaxleCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='frontloadaxleCu',
            field=models.DecimalField(blank=True, db_column='FrontloadaxleCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='frontloadaxleDkm',
            field=models.DecimalField(blank=True, db_column='FrontloadaxleDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='frontloadaxleQ',
            field=models.DecimalField(blank=True, db_column='FrontloadaxleQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='fronttiresCkm',
            field=models.DecimalField(blank=True, db_column='FronttiresCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='fronttiresCu',
            field=models.DecimalField(blank=True, db_column='FronttiresCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='fronttiresDkm',
            field=models.DecimalField(blank=True, db_column='FronttiresDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='fronttiresQ',
            field=models.DecimalField(blank=True, db_column='FronttiresQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='fuelpumpCkm',
            field=models.DecimalField(blank=True, db_column='FuelpumpCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='fuelpumpCu',
            field=models.DecimalField(blank=True, db_column='FuelpumpCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='fuelpumpDkm',
            field=models.DecimalField(blank=True, db_column='FuelpumpDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='fuelpumpQ',
            field=models.DecimalField(blank=True, db_column='FuelpumpQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='glassesandcleaningsystemCkm',
            field=models.DecimalField(blank=True, db_column='GlassesandcleaningsystemCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='glassesandcleaningsystemCu',
            field=models.DecimalField(blank=True, db_column='GlassesandcleaningsystemCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='glassesandcleaningsystemDkm',
            field=models.DecimalField(blank=True, db_column='GlassesandcleaningsystemDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='glassesandcleaningsystemQ',
            field=models.DecimalField(blank=True, db_column='GlassesandcleaningsystemQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='intonationtuningCkm',
            field=models.DecimalField(blank=True, db_column='IntonationtuningCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='intonationtuningCu',
            field=models.DecimalField(blank=True, db_column='IntonationtuningCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='intonationtuningDkm',
            field=models.DecimalField(blank=True, db_column='IntonationtuningDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='intonationtuningQ',
            field=models.DecimalField(blank=True, db_column='IntonationtuningQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='lightsCkm',
            field=models.DecimalField(blank=True, db_column='LightsCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='lightsCu',
            field=models.DecimalField(blank=True, db_column='LightsCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='lightsDkm',
            field=models.DecimalField(blank=True, db_column='LightsDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='lightsQ',
            field=models.DecimalField(blank=True, db_column='LightsQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='lubricantsfluidsCkm',
            field=models.DecimalField(blank=True, db_column='LubricantsfluidsCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='lubricantsfluidsCu',
            field=models.DecimalField(blank=True, db_column='LubricantsfluidsCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='lubricantsfluidsDkm',
            field=models.DecimalField(blank=True, db_column='LubricantsfluidsDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='lubricantsfluidsQ',
            field=models.DecimalField(blank=True, db_column='LubricantsfluidsQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='majorrepairCkm',
            field=models.DecimalField(blank=True, db_column='MajorrepairCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='majorrepairCu',
            field=models.DecimalField(blank=True, db_column='MajorrepairCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='majorrepairDkm',
            field=models.DecimalField(blank=True, db_column='MajorrepairDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='majorrepairQ',
            field=models.DecimalField(blank=True, db_column='MajorrepairQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='minorrepairCkm',
            field=models.DecimalField(blank=True, db_column='MinorrepairCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='minorrepairCu',
            field=models.DecimalField(blank=True, db_column='MinorrepairCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='minorrepairDkm',
            field=models.DecimalField(blank=True, db_column='MinorrepairDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='minorrepairQ',
            field=models.DecimalField(blank=True, db_column='MinorrepairQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='oilchangeCkm',
            field=models.DecimalField(blank=True, db_column='OilchangeCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='oilchangeCu',
            field=models.DecimalField(blank=True, db_column='OilchangeCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='oilchangeDkm',
            field=models.DecimalField(blank=True, db_column='OilchangeDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='oilchangeQ',
            field=models.DecimalField(blank=True, db_column='OilchangeQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='oilsystemCkm',
            field=models.DecimalField(blank=True, db_column='OilsystemCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='oilsystemCu',
            field=models.DecimalField(blank=True, db_column='OilsystemCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='oilsystemDkm',
            field=models.DecimalField(blank=True, db_column='OilsystemDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='oilsystemQ',
            field=models.DecimalField(blank=True, db_column='OilsystemQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='pinCkm',
            field=models.DecimalField(blank=True, db_column='PinCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='pinCu',
            field=models.DecimalField(blank=True, db_column='PinCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='pinDkm',
            field=models.DecimalField(blank=True, db_column='PinDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='pinQ',
            field=models.DecimalField(blank=True, db_column='PinQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='pressuregaugesCkm',
            field=models.DecimalField(blank=True, db_column='PressuregaugesCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='pressuregaugesCu',
            field=models.DecimalField(blank=True, db_column='PressuregaugesCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='pressuregaugesDkm',
            field=models.DecimalField(blank=True, db_column='PressuregaugesDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='pressuregaugesQ',
            field=models.DecimalField(blank=True, db_column='PressuregaugesQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='puncturesanddamageCkm',
            field=models.DecimalField(blank=True, db_column='PuncturesanddamageCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='puncturesanddamageCu',
            field=models.DecimalField(blank=True, db_column='PuncturesanddamageCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='puncturesanddamageDkm',
            field=models.DecimalField(blank=True, db_column='PuncturesanddamageDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='puncturesanddamageQ',
            field=models.DecimalField(blank=True, db_column='PuncturesanddamageQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='radiatorCkm',
            field=models.DecimalField(blank=True, db_column='RadiatorCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='radiatorCu',
            field=models.DecimalField(blank=True, db_column='RadiatorCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='radiatorDkm',
            field=models.DecimalField(blank=True, db_column='RadiatorDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='radiatorQ',
            field=models.DecimalField(blank=True, db_column='RadiatorQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='rearloadaxleCkm',
            field=models.DecimalField(blank=True, db_column='RearloadaxleCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='rearloadaxleCu',
            field=models.DecimalField(blank=True, db_column='RearloadaxleCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='rearloadaxleDkm',
            field=models.DecimalField(blank=True, db_column='RearloadaxleDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='rearloadaxleQ',
            field=models.DecimalField(blank=True, db_column='RearloadaxleQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='rubberCkm',
            field=models.DecimalField(blank=True, db_column='RubberCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='rubberCu',
            field=models.DecimalField(blank=True, db_column='RubberCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='rubberDkm',
            field=models.DecimalField(blank=True, db_column='RubberDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='rubberQ',
            field=models.DecimalField(blank=True, db_column='RubberQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='sealsCkm',
            field=models.DecimalField(blank=True, db_column='SealsCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='sealsCu',
            field=models.DecimalField(blank=True, db_column='SealsCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='sealsDkm',
            field=models.DecimalField(blank=True, db_column='SealsDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='sealsQ',
            field=models.DecimalField(blank=True, db_column='SealsQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='springsleafspringsCkm',
            field=models.DecimalField(blank=True, db_column='SpringsleafspringsCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='springsleafspringsCu',
            field=models.DecimalField(blank=True, db_column='SpringsleafspringsCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='springsleafspringsDkm',
            field=models.DecimalField(blank=True, db_column='SpringsleafspringsDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='springsleafspringsQ',
            field=models.DecimalField(blank=True, db_column='SpringsleafspringsQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='startingmotorCkm',
            field=models.DecimalField(blank=True, db_column='StartingmotorCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='startingmotorCu',
            field=models.DecimalField(blank=True, db_column='StartingmotorCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='startingmotorDkm',
            field=models.DecimalField(blank=True, db_column='StartingmotorDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='startingmotorQ',
            field=models.DecimalField(blank=True, db_column='StartingmotorQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='swingingCkm',
            field=models.DecimalField(blank=True, db_column='SwingingCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='swingingCu',
            field=models.DecimalField(blank=True, db_column='SwingingCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='swingingDkm',
            field=models.DecimalField(blank=True, db_column='SwingingDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='swingingQ',
            field=models.DecimalField(blank=True, db_column='SwingingQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='total',
            field=models.DecimalField(blank=True, db_column='Total', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='transmissiondifferentialCkm',
            field=models.DecimalField(blank=True, db_column='TransmissiondifferentialCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='transmissiondifferentialCu',
            field=models.DecimalField(blank=True, db_column='TransmissiondifferentialCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='transmissiondifferentialDkm',
            field=models.DecimalField(blank=True, db_column='TransmissiondifferentialDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='transmissiondifferentialQ',
            field=models.DecimalField(blank=True, db_column='TransmissiondifferentialQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='turboCkm',
            field=models.DecimalField(blank=True, db_column='TurboCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='turboCu',
            field=models.DecimalField(blank=True, db_column='TurboCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='turboDkm',
            field=models.DecimalField(blank=True, db_column='TurboDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='turboQ',
            field=models.DecimalField(blank=True, db_column='TurboQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='waterpumpCkm',
            field=models.DecimalField(blank=True, db_column='WaterpumpCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='waterpumpCu',
            field=models.DecimalField(blank=True, db_column='WaterpumpCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='waterpumpDkm',
            field=models.DecimalField(blank=True, db_column='WaterpumpDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='waterpumpQ',
            field=models.DecimalField(blank=True, db_column='WaterpumpQ', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='wheelsCkm',
            field=models.DecimalField(blank=True, db_column='WheelsCkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='wheelsCu',
            field=models.DecimalField(blank=True, db_column='WheelsCu', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='wheelsDkm',
            field=models.DecimalField(blank=True, db_column='WheelsDkm', decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='maintenamcecosts',
            name='wheelsQ',
            field=models.DecimalField(blank=True, db_column='WheelsQ', decimal_places=5, max_digits=15, null=True),
        ),
    ]
