# Generated by Django 4.2.1 on 2023-06-09 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_remove_historicalmaintenamcecosts_brakingsystem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='acCu',
            field=models.DecimalField(blank=True, db_column='AcCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='acDkm',
            field=models.IntegerField(blank=True, db_column='AcDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='acQ',
            field=models.IntegerField(blank=True, db_column='AcQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='accessoriesCu',
            field=models.DecimalField(blank=True, db_column='AccessoriesCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='accessoriesDkm',
            field=models.IntegerField(blank=True, db_column='AccessoriesDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='accessoriesQ',
            field=models.IntegerField(blank=True, db_column='AccessoriesQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='addressCu',
            field=models.DecimalField(blank=True, db_column='AddressCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='addressDkm',
            field=models.IntegerField(blank=True, db_column='AddressDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='addressQ',
            field=models.IntegerField(blank=True, db_column='AddressQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='adjustmentscalibrationsCu',
            field=models.DecimalField(blank=True, db_column='AdjustmentscalibrationsCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='adjustmentscalibrationsDkm',
            field=models.IntegerField(blank=True, db_column='AdjustmentscalibrationsDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='adjustmentscalibrationsQ',
            field=models.IntegerField(blank=True, db_column='AdjustmentscalibrationsQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='airfiltersCu',
            field=models.DecimalField(blank=True, db_column='AirfiltersCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='airfiltersDkm',
            field=models.IntegerField(blank=True, db_column='AirfiltersDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='airfiltersQ',
            field=models.IntegerField(blank=True, db_column='AirfiltersQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='airpurifierCu',
            field=models.DecimalField(blank=True, db_column='AirpurifierCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='airpurifierDkm',
            field=models.IntegerField(blank=True, db_column='AirpurifierDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='airpurifierQ',
            field=models.IntegerField(blank=True, db_column='AirpurifierQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='alignmentCu',
            field=models.DecimalField(blank=True, db_column='AlignmentCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='alignmentDkm',
            field=models.IntegerField(blank=True, db_column='AlignmentDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='alignmentQ',
            field=models.IntegerField(blank=True, db_column='AlignmentQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='alternatorCu',
            field=models.DecimalField(blank=True, db_column='AlternatorCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='alternatorDkm',
            field=models.IntegerField(blank=True, db_column='AlternatorDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='alternatorQ',
            field=models.IntegerField(blank=True, db_column='AlternatorQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='batteriesCu',
            field=models.DecimalField(blank=True, db_column='BatteriesCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='batteriesDkm',
            field=models.IntegerField(blank=True, db_column='BatteriesDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='batteriesQ',
            field=models.IntegerField(blank=True, db_column='BatteriesQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='boxCu',
            field=models.DecimalField(blank=True, db_column='BoxCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='boxDkm',
            field=models.IntegerField(blank=True, db_column='BoxDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='boxQ',
            field=models.IntegerField(blank=True, db_column='BoxQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='cardanCu',
            field=models.DecimalField(blank=True, db_column='CardanCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='cardanDkm',
            field=models.IntegerField(blank=True, db_column='CardanDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='cardanQ',
            field=models.IntegerField(blank=True, db_column='CardanQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='casetransmissionoilCu',
            field=models.DecimalField(blank=True, db_column='CasetransmissionoilCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='casetransmissionoilDkm',
            field=models.IntegerField(blank=True, db_column='CasetransmissionoilDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='casetransmissionoilQ',
            field=models.IntegerField(blank=True, db_column='CasetransmissionoilQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='cleaningCu',
            field=models.DecimalField(blank=True, db_column='CleaningCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='cleaningDkm',
            field=models.IntegerField(blank=True, db_column='CleaningDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='cleaningQ',
            field=models.IntegerField(blank=True, db_column='CleaningQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='clutchclutchCu',
            field=models.DecimalField(blank=True, db_column='ClutchclutchCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='clutchclutchDkm',
            field=models.IntegerField(blank=True, db_column='ClutchclutchDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='clutchclutchQ',
            field=models.IntegerField(blank=True, db_column='ClutchclutchQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='coolingCu',
            field=models.DecimalField(blank=True, db_column='CoolingCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='coolingDkm',
            field=models.IntegerField(blank=True, db_column='CoolingDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='coolingQ',
            field=models.IntegerField(blank=True, db_column='CoolingQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='dragtiresCu',
            field=models.DecimalField(blank=True, db_column='DragtiresCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='dragtiresDkm',
            field=models.IntegerField(blank=True, db_column='DragtiresDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='dragtiresQ',
            field=models.IntegerField(blank=True, db_column='DragtiresQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='drivetiresCu',
            field=models.DecimalField(blank=True, db_column='DrivetiresCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='drivetiresDkm',
            field=models.IntegerField(blank=True, db_column='DrivetiresDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='drivetiresQ',
            field=models.IntegerField(blank=True, db_column='DrivetiresQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='drumsCu',
            field=models.DecimalField(blank=True, db_column='DrumsCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='drumsDkm',
            field=models.IntegerField(blank=True, db_column='DrumsDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='drumsQ',
            field=models.IntegerField(blank=True, db_column='DrumsQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='electronicsystemCu',
            field=models.DecimalField(blank=True, db_column='ElectronicsystemCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='electronicsystemDkm',
            field=models.IntegerField(blank=True, db_column='ElectronicsystemDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='electronicsystemQ',
            field=models.IntegerField(blank=True, db_column='ElectronicsystemQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='engineoverhaulCu',
            field=models.DecimalField(blank=True, db_column='EngineoverhaulCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='engineoverhaulDkm',
            field=models.IntegerField(blank=True, db_column='EngineoverhaulDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='engineoverhaulQ',
            field=models.IntegerField(blank=True, db_column='EngineoverhaulQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='exhaustsystemCu',
            field=models.DecimalField(blank=True, db_column='ExhaustsystemCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='exhaustsystemDkm',
            field=models.IntegerField(blank=True, db_column='ExhaustsystemDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='exhaustsystemQ',
            field=models.IntegerField(blank=True, db_column='ExhaustsystemQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='frontloadaxleCu',
            field=models.DecimalField(blank=True, db_column='FrontloadaxleCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='frontloadaxleDkm',
            field=models.IntegerField(blank=True, db_column='FrontloadaxleDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='frontloadaxleQ',
            field=models.IntegerField(blank=True, db_column='FrontloadaxleQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='fronttiresCu',
            field=models.DecimalField(blank=True, db_column='FronttiresCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='fronttiresDkm',
            field=models.IntegerField(blank=True, db_column='FronttiresDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='fronttiresQ',
            field=models.IntegerField(blank=True, db_column='FronttiresQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='fuelpumpCu',
            field=models.DecimalField(blank=True, db_column='FuelpumpCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='fuelpumpDkm',
            field=models.IntegerField(blank=True, db_column='FuelpumpDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='fuelpumpQ',
            field=models.IntegerField(blank=True, db_column='FuelpumpQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='glassesandcleaningsystemCu',
            field=models.DecimalField(blank=True, db_column='GlassesandcleaningsystemCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='glassesandcleaningsystemDkm',
            field=models.IntegerField(blank=True, db_column='GlassesandcleaningsystemDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='glassesandcleaningsystemQ',
            field=models.IntegerField(blank=True, db_column='GlassesandcleaningsystemQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='intonationtuningCu',
            field=models.DecimalField(blank=True, db_column='IntonationtuningCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='intonationtuningDkm',
            field=models.IntegerField(blank=True, db_column='IntonationtuningDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='intonationtuningQ',
            field=models.IntegerField(blank=True, db_column='IntonationtuningQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='lightsCu',
            field=models.DecimalField(blank=True, db_column='LightsCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='lightsDkm',
            field=models.IntegerField(blank=True, db_column='LightsDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='lightsQ',
            field=models.IntegerField(blank=True, db_column='LightsQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='lubricantsfluidsCu',
            field=models.DecimalField(blank=True, db_column='LubricantsfluidsCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='lubricantsfluidsDkm',
            field=models.IntegerField(blank=True, db_column='LubricantsfluidsDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='lubricantsfluidsQ',
            field=models.IntegerField(blank=True, db_column='LubricantsfluidsQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='majorrepairCu',
            field=models.DecimalField(blank=True, db_column='MajorrepairCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='majorrepairDkm',
            field=models.IntegerField(blank=True, db_column='MajorrepairDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='majorrepairQ',
            field=models.IntegerField(blank=True, db_column='MajorrepairQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='minorrepairCu',
            field=models.DecimalField(blank=True, db_column='MinorrepairCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='minorrepairDkm',
            field=models.IntegerField(blank=True, db_column='MinorrepairDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='minorrepairQ',
            field=models.IntegerField(blank=True, db_column='MinorrepairQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='oilchangeCu',
            field=models.DecimalField(blank=True, db_column='OilchangeCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='oilchangeDkm',
            field=models.IntegerField(blank=True, db_column='OilchangeDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='oilchangeQ',
            field=models.IntegerField(blank=True, db_column='OilchangeQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='oilsystemCu',
            field=models.DecimalField(blank=True, db_column='OilsystemCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='oilsystemDkm',
            field=models.IntegerField(blank=True, db_column='OilsystemDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='oilsystemQ',
            field=models.IntegerField(blank=True, db_column='OilsystemQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='pinCu',
            field=models.DecimalField(blank=True, db_column='PinCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='pinDkm',
            field=models.IntegerField(blank=True, db_column='PinDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='pinQ',
            field=models.IntegerField(blank=True, db_column='PinQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='pressuregaugesCu',
            field=models.DecimalField(blank=True, db_column='PressuregaugesCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='pressuregaugesDkm',
            field=models.IntegerField(blank=True, db_column='PressuregaugesDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='pressuregaugesQ',
            field=models.IntegerField(blank=True, db_column='PressuregaugesQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='puncturesanddamageCu',
            field=models.DecimalField(blank=True, db_column='PuncturesanddamageCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='puncturesanddamageDkm',
            field=models.IntegerField(blank=True, db_column='PuncturesanddamageDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='puncturesanddamageQ',
            field=models.IntegerField(blank=True, db_column='PuncturesanddamageQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='radiatorCu',
            field=models.DecimalField(blank=True, db_column='RadiatorCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='radiatorDkm',
            field=models.IntegerField(blank=True, db_column='RadiatorDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='radiatorQ',
            field=models.IntegerField(blank=True, db_column='RadiatorQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='rearloadaxleCu',
            field=models.DecimalField(blank=True, db_column='RearloadaxleCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='rearloadaxleDkm',
            field=models.IntegerField(blank=True, db_column='RearloadaxleDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='rearloadaxleQ',
            field=models.IntegerField(blank=True, db_column='RearloadaxleQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='rubberCu',
            field=models.DecimalField(blank=True, db_column='RubberCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='rubberDkm',
            field=models.IntegerField(blank=True, db_column='RubberDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='rubberQ',
            field=models.IntegerField(blank=True, db_column='RubberQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='sealsCu',
            field=models.DecimalField(blank=True, db_column='SealsCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='sealsDkm',
            field=models.IntegerField(blank=True, db_column='SealsDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='sealsQ',
            field=models.IntegerField(blank=True, db_column='SealsQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='springsleafspringsCu',
            field=models.DecimalField(blank=True, db_column='SpringsleafspringsCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='springsleafspringsDkm',
            field=models.IntegerField(blank=True, db_column='SpringsleafspringsDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='springsleafspringsQ',
            field=models.IntegerField(blank=True, db_column='SpringsleafspringsQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='startingmotorCu',
            field=models.DecimalField(blank=True, db_column='StartingmotorCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='startingmotorDkm',
            field=models.IntegerField(blank=True, db_column='StartingmotorDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='startingmotorQ',
            field=models.IntegerField(blank=True, db_column='StartingmotorQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='swingingCu',
            field=models.DecimalField(blank=True, db_column='SwingingCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='swingingDkm',
            field=models.IntegerField(blank=True, db_column='SwingingDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='swingingQ',
            field=models.IntegerField(blank=True, db_column='SwingingQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='transmissiondifferentialCu',
            field=models.DecimalField(blank=True, db_column='TransmissiondifferentialCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='transmissiondifferentialDkm',
            field=models.IntegerField(blank=True, db_column='TransmissiondifferentialDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='transmissiondifferentialQ',
            field=models.IntegerField(blank=True, db_column='TransmissiondifferentialQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='turboCu',
            field=models.DecimalField(blank=True, db_column='TurboCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='turboDkm',
            field=models.IntegerField(blank=True, db_column='TurboDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='turboQ',
            field=models.IntegerField(blank=True, db_column='TurboQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='waterpumpCu',
            field=models.DecimalField(blank=True, db_column='WaterpumpCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='waterpumpDkm',
            field=models.IntegerField(blank=True, db_column='WaterpumpDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='waterpumpQ',
            field=models.IntegerField(blank=True, db_column='WaterpumpQ', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='wheelsCu',
            field=models.DecimalField(blank=True, db_column='WheelsCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='wheelsDkm',
            field=models.IntegerField(blank=True, db_column='WheelsDkm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='wheelsQ',
            field=models.IntegerField(blank=True, db_column='WheelsQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='acCu',
            field=models.DecimalField(blank=True, db_column='AcCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='acDkm',
            field=models.IntegerField(blank=True, db_column='AcDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='acQ',
            field=models.IntegerField(blank=True, db_column='AcQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='accessoriesCu',
            field=models.DecimalField(blank=True, db_column='AccessoriesCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='accessoriesDkm',
            field=models.IntegerField(blank=True, db_column='AccessoriesDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='accessoriesQ',
            field=models.IntegerField(blank=True, db_column='AccessoriesQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='addressCu',
            field=models.DecimalField(blank=True, db_column='AddressCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='addressDkm',
            field=models.IntegerField(blank=True, db_column='AddressDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='addressQ',
            field=models.IntegerField(blank=True, db_column='AddressQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='adjustmentscalibrationsCu',
            field=models.DecimalField(blank=True, db_column='AdjustmentscalibrationsCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='adjustmentscalibrationsDkm',
            field=models.IntegerField(blank=True, db_column='AdjustmentscalibrationsDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='adjustmentscalibrationsQ',
            field=models.IntegerField(blank=True, db_column='AdjustmentscalibrationsQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='airfiltersCu',
            field=models.DecimalField(blank=True, db_column='AirfiltersCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='airfiltersDkm',
            field=models.IntegerField(blank=True, db_column='AirfiltersDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='airfiltersQ',
            field=models.IntegerField(blank=True, db_column='AirfiltersQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='airpurifierCu',
            field=models.DecimalField(blank=True, db_column='AirpurifierCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='airpurifierDkm',
            field=models.IntegerField(blank=True, db_column='AirpurifierDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='airpurifierQ',
            field=models.IntegerField(blank=True, db_column='AirpurifierQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='alignmentCu',
            field=models.DecimalField(blank=True, db_column='AlignmentCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='alignmentDkm',
            field=models.IntegerField(blank=True, db_column='AlignmentDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='alignmentQ',
            field=models.IntegerField(blank=True, db_column='AlignmentQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='alternatorCu',
            field=models.DecimalField(blank=True, db_column='AlternatorCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='alternatorDkm',
            field=models.IntegerField(blank=True, db_column='AlternatorDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='alternatorQ',
            field=models.IntegerField(blank=True, db_column='AlternatorQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='batteriesCu',
            field=models.DecimalField(blank=True, db_column='BatteriesCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='batteriesDkm',
            field=models.IntegerField(blank=True, db_column='BatteriesDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='batteriesQ',
            field=models.IntegerField(blank=True, db_column='BatteriesQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='boxCu',
            field=models.DecimalField(blank=True, db_column='BoxCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='boxDkm',
            field=models.IntegerField(blank=True, db_column='BoxDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='boxQ',
            field=models.IntegerField(blank=True, db_column='BoxQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='cardanCu',
            field=models.DecimalField(blank=True, db_column='CardanCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='cardanDkm',
            field=models.IntegerField(blank=True, db_column='CardanDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='cardanQ',
            field=models.IntegerField(blank=True, db_column='CardanQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='casetransmissionoilCu',
            field=models.DecimalField(blank=True, db_column='CasetransmissionoilCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='casetransmissionoilDkm',
            field=models.IntegerField(blank=True, db_column='CasetransmissionoilDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='casetransmissionoilQ',
            field=models.IntegerField(blank=True, db_column='CasetransmissionoilQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='cleaningCu',
            field=models.DecimalField(blank=True, db_column='CleaningCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='cleaningDkm',
            field=models.IntegerField(blank=True, db_column='CleaningDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='cleaningQ',
            field=models.IntegerField(blank=True, db_column='CleaningQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='clutchclutchCu',
            field=models.DecimalField(blank=True, db_column='ClutchclutchCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='clutchclutchDkm',
            field=models.IntegerField(blank=True, db_column='ClutchclutchDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='clutchclutchQ',
            field=models.IntegerField(blank=True, db_column='ClutchclutchQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='coolingCu',
            field=models.DecimalField(blank=True, db_column='CoolingCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='coolingDkm',
            field=models.IntegerField(blank=True, db_column='CoolingDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='coolingQ',
            field=models.IntegerField(blank=True, db_column='CoolingQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='dragtiresCu',
            field=models.DecimalField(blank=True, db_column='DragtiresCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='dragtiresDkm',
            field=models.IntegerField(blank=True, db_column='DragtiresDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='dragtiresQ',
            field=models.IntegerField(blank=True, db_column='DragtiresQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='drivetiresCu',
            field=models.DecimalField(blank=True, db_column='DrivetiresCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='drivetiresDkm',
            field=models.IntegerField(blank=True, db_column='DrivetiresDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='drivetiresQ',
            field=models.IntegerField(blank=True, db_column='DrivetiresQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='drumsCu',
            field=models.DecimalField(blank=True, db_column='DrumsCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='drumsDkm',
            field=models.IntegerField(blank=True, db_column='DrumsDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='drumsQ',
            field=models.IntegerField(blank=True, db_column='DrumsQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='electronicsystemCu',
            field=models.DecimalField(blank=True, db_column='ElectronicsystemCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='electronicsystemDkm',
            field=models.IntegerField(blank=True, db_column='ElectronicsystemDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='electronicsystemQ',
            field=models.IntegerField(blank=True, db_column='ElectronicsystemQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='engineoverhaulCu',
            field=models.DecimalField(blank=True, db_column='EngineoverhaulCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='engineoverhaulDkm',
            field=models.IntegerField(blank=True, db_column='EngineoverhaulDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='engineoverhaulQ',
            field=models.IntegerField(blank=True, db_column='EngineoverhaulQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='exhaustsystemCu',
            field=models.DecimalField(blank=True, db_column='ExhaustsystemCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='exhaustsystemDkm',
            field=models.IntegerField(blank=True, db_column='ExhaustsystemDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='exhaustsystemQ',
            field=models.IntegerField(blank=True, db_column='ExhaustsystemQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='frontloadaxleCu',
            field=models.DecimalField(blank=True, db_column='FrontloadaxleCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='frontloadaxleDkm',
            field=models.IntegerField(blank=True, db_column='FrontloadaxleDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='frontloadaxleQ',
            field=models.IntegerField(blank=True, db_column='FrontloadaxleQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='fronttiresCu',
            field=models.DecimalField(blank=True, db_column='FronttiresCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='fronttiresDkm',
            field=models.IntegerField(blank=True, db_column='FronttiresDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='fronttiresQ',
            field=models.IntegerField(blank=True, db_column='FronttiresQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='fuelpumpCu',
            field=models.DecimalField(blank=True, db_column='FuelpumpCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='fuelpumpDkm',
            field=models.IntegerField(blank=True, db_column='FuelpumpDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='fuelpumpQ',
            field=models.IntegerField(blank=True, db_column='FuelpumpQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='glassesandcleaningsystemCu',
            field=models.DecimalField(blank=True, db_column='GlassesandcleaningsystemCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='glassesandcleaningsystemDkm',
            field=models.IntegerField(blank=True, db_column='GlassesandcleaningsystemDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='glassesandcleaningsystemQ',
            field=models.IntegerField(blank=True, db_column='GlassesandcleaningsystemQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='intonationtuningCu',
            field=models.DecimalField(blank=True, db_column='IntonationtuningCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='intonationtuningDkm',
            field=models.IntegerField(blank=True, db_column='IntonationtuningDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='intonationtuningQ',
            field=models.IntegerField(blank=True, db_column='IntonationtuningQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='lightsCu',
            field=models.DecimalField(blank=True, db_column='LightsCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='lightsDkm',
            field=models.IntegerField(blank=True, db_column='LightsDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='lightsQ',
            field=models.IntegerField(blank=True, db_column='LightsQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='lubricantsfluidsCu',
            field=models.DecimalField(blank=True, db_column='LubricantsfluidsCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='lubricantsfluidsDkm',
            field=models.IntegerField(blank=True, db_column='LubricantsfluidsDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='lubricantsfluidsQ',
            field=models.IntegerField(blank=True, db_column='LubricantsfluidsQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='majorrepairCu',
            field=models.DecimalField(blank=True, db_column='MajorrepairCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='majorrepairDkm',
            field=models.IntegerField(blank=True, db_column='MajorrepairDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='majorrepairQ',
            field=models.IntegerField(blank=True, db_column='MajorrepairQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='minorrepairCu',
            field=models.DecimalField(blank=True, db_column='MinorrepairCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='minorrepairDkm',
            field=models.IntegerField(blank=True, db_column='MinorrepairDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='minorrepairQ',
            field=models.IntegerField(blank=True, db_column='MinorrepairQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='oilchangeCu',
            field=models.DecimalField(blank=True, db_column='OilchangeCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='oilchangeDkm',
            field=models.IntegerField(blank=True, db_column='OilchangeDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='oilchangeQ',
            field=models.IntegerField(blank=True, db_column='OilchangeQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='oilsystemCu',
            field=models.DecimalField(blank=True, db_column='OilsystemCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='oilsystemDkm',
            field=models.IntegerField(blank=True, db_column='OilsystemDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='oilsystemQ',
            field=models.IntegerField(blank=True, db_column='OilsystemQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='pinCu',
            field=models.DecimalField(blank=True, db_column='PinCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='pinDkm',
            field=models.IntegerField(blank=True, db_column='PinDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='pinQ',
            field=models.IntegerField(blank=True, db_column='PinQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='pressuregaugesCu',
            field=models.DecimalField(blank=True, db_column='PressuregaugesCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='pressuregaugesDkm',
            field=models.IntegerField(blank=True, db_column='PressuregaugesDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='pressuregaugesQ',
            field=models.IntegerField(blank=True, db_column='PressuregaugesQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='puncturesanddamageCu',
            field=models.DecimalField(blank=True, db_column='PuncturesanddamageCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='puncturesanddamageDkm',
            field=models.IntegerField(blank=True, db_column='PuncturesanddamageDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='puncturesanddamageQ',
            field=models.IntegerField(blank=True, db_column='PuncturesanddamageQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='radiatorCu',
            field=models.DecimalField(blank=True, db_column='RadiatorCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='radiatorDkm',
            field=models.IntegerField(blank=True, db_column='RadiatorDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='radiatorQ',
            field=models.IntegerField(blank=True, db_column='RadiatorQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='rearloadaxleCu',
            field=models.DecimalField(blank=True, db_column='RearloadaxleCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='rearloadaxleDkm',
            field=models.IntegerField(blank=True, db_column='RearloadaxleDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='rearloadaxleQ',
            field=models.IntegerField(blank=True, db_column='RearloadaxleQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='rubberCu',
            field=models.DecimalField(blank=True, db_column='RubberCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='rubberDkm',
            field=models.IntegerField(blank=True, db_column='RubberDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='rubberQ',
            field=models.IntegerField(blank=True, db_column='RubberQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='sealsCu',
            field=models.DecimalField(blank=True, db_column='SealsCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='sealsDkm',
            field=models.IntegerField(blank=True, db_column='SealsDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='sealsQ',
            field=models.IntegerField(blank=True, db_column='SealsQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='springsleafspringsCu',
            field=models.DecimalField(blank=True, db_column='SpringsleafspringsCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='springsleafspringsDkm',
            field=models.IntegerField(blank=True, db_column='SpringsleafspringsDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='springsleafspringsQ',
            field=models.IntegerField(blank=True, db_column='SpringsleafspringsQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='startingmotorCu',
            field=models.DecimalField(blank=True, db_column='StartingmotorCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='startingmotorDkm',
            field=models.IntegerField(blank=True, db_column='StartingmotorDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='startingmotorQ',
            field=models.IntegerField(blank=True, db_column='StartingmotorQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='swingingCu',
            field=models.DecimalField(blank=True, db_column='SwingingCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='swingingDkm',
            field=models.IntegerField(blank=True, db_column='SwingingDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='swingingQ',
            field=models.IntegerField(blank=True, db_column='SwingingQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='transmissiondifferentialCu',
            field=models.DecimalField(blank=True, db_column='TransmissiondifferentialCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='transmissiondifferentialDkm',
            field=models.IntegerField(blank=True, db_column='TransmissiondifferentialDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='transmissiondifferentialQ',
            field=models.IntegerField(blank=True, db_column='TransmissiondifferentialQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='turboCu',
            field=models.DecimalField(blank=True, db_column='TurboCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='turboDkm',
            field=models.IntegerField(blank=True, db_column='TurboDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='turboQ',
            field=models.IntegerField(blank=True, db_column='TurboQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='waterpumpCu',
            field=models.DecimalField(blank=True, db_column='WaterpumpCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='waterpumpDkm',
            field=models.IntegerField(blank=True, db_column='WaterpumpDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='waterpumpQ',
            field=models.IntegerField(blank=True, db_column='WaterpumpQ', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='wheelsCu',
            field=models.DecimalField(blank=True, db_column='WheelsCu', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='wheelsDkm',
            field=models.IntegerField(blank=True, db_column='WheelsDkm', null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='wheelsQ',
            field=models.IntegerField(blank=True, db_column='WheelsQ', null=True),
        ),
    ]
