# Generated by Django 4.2.1 on 2023-06-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_alter_historicalmaintenamcecosts_accu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmaintenamcecosts',
            name='total',
            field=models.DecimalField(blank=True, db_column='Total', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenamcecosts',
            name='total',
            field=models.DecimalField(blank=True, db_column='Total', decimal_places=2, max_digits=15, null=True),
        ),
    ]
