# Generated by Django 4.2.1 on 2023-06-10 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_historicalfixedcosts_fixedcosts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalfixedcosts',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical fixed costs', 'verbose_name_plural': 'historical fixed costss'},
        ),
    ]
