# Generated by Django 4.2.1 on 2023-06-06 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDestinations',
            fields=[
                ('iddestinations', models.IntegerField(blank=True, db_column='IdDestinations', db_index=True)),
                ('destinations', models.CharField(db_column='destinations', max_length=250)),
                ('latitude', models.FloatField(blank=True, db_column='Latitude', null=True)),
                ('longitude', models.FloatField(blank=True, db_column='Longitude', null=True)),
                ('state', models.BooleanField(db_column='State', default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('idprovince', models.ForeignKey(blank=True, db_column='IdProvince', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.province')),
            ],
            options={
                'verbose_name': 'historical destinations',
                'verbose_name_plural': 'historical destinationss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCellars',
            fields=[
                ('idcellars', models.IntegerField(blank=True, db_column='IdCellars', db_index=True)),
                ('cellar', models.CharField(db_column='Cellar', max_length=250)),
                ('latitude', models.FloatField(blank=True, db_column='Latitude', null=True)),
                ('longitude', models.FloatField(blank=True, db_column='Longitude', null=True)),
                ('state', models.BooleanField(db_column='State', default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('idprovince', models.ForeignKey(blank=True, db_column='IdProvince', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.province')),
            ],
            options={
                'verbose_name': 'historical cellars',
                'verbose_name_plural': 'historical cellarss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('iddestinations', models.AutoField(db_column='IdDestinations', primary_key=True, serialize=False)),
                ('destinations', models.CharField(db_column='destinations', max_length=250)),
                ('latitude', models.FloatField(blank=True, db_column='Latitude', null=True)),
                ('longitude', models.FloatField(blank=True, db_column='Longitude', null=True)),
                ('state', models.BooleanField(db_column='State', default=True)),
                ('idprovince', models.ForeignKey(db_column='IdProvince', on_delete=django.db.models.deletion.CASCADE, to='company.province')),
            ],
        ),
        migrations.CreateModel(
            name='Cellars',
            fields=[
                ('idcellars', models.AutoField(db_column='IdCellars', primary_key=True, serialize=False)),
                ('cellar', models.CharField(db_column='Cellar', max_length=250)),
                ('latitude', models.FloatField(blank=True, db_column='Latitude', null=True)),
                ('longitude', models.FloatField(blank=True, db_column='Longitude', null=True)),
                ('state', models.BooleanField(db_column='State', default=True)),
                ('idprovince', models.ForeignKey(db_column='IdProvince', on_delete=django.db.models.deletion.CASCADE, to='company.province')),
            ],
        ),
    ]
