# Generated by Django 4.2.1 on 2023-06-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_concepts_historicalconcepts_historicalbill_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='idtabulation',
            field=models.IntegerField(blank=True, db_column='IdTabulation', null=True),
        ),
        migrations.AddField(
            model_name='historicalbill',
            name='idtabulation',
            field=models.IntegerField(blank=True, db_column='IdTabulation', null=True),
        ),
    ]
