# Generated by Django 4.2.1 on 2023-06-20 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_bill_idtabulation_historicalbill_idtabulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='idtabulation',
            field=models.ForeignKey(db_column='IdTabulation', on_delete=django.db.models.deletion.CASCADE, to='routes.tabulation'),
        ),
        migrations.AlterField(
            model_name='historicalbill',
            name='idtabulation',
            field=models.ForeignKey(blank=True, db_column='IdTabulation', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='routes.tabulation'),
        ),
    ]
