# Generated by Django 4.2.1 on 2023-06-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_alter_bill_idtabulation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltabulation',
            name='idcellars',
        ),
        migrations.RemoveField(
            model_name='tabulation',
            name='idcellars',
        ),
        migrations.AddField(
            model_name='historicaltabulation',
            name='idlocation',
            field=models.IntegerField(blank=True, db_column='IdLocation', null=True),
        ),
        migrations.AddField(
            model_name='tabulation',
            name='idlocation',
            field=models.IntegerField(blank=True, db_column='IdLocation', null=True),
        ),
    ]
