# Generated by Django 4.2.1 on 2023-06-06 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('idcompany', models.AutoField(db_column='IdCompany', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('logo', models.ImageField(blank=True, db_column='Logo', max_length=255, null=True, upload_to='logo/')),
                ('ruc', models.CharField(db_column='Ruc', max_length=13)),
                ('address', models.CharField(db_column='Address', max_length=255)),
                ('email', models.CharField(db_column='Email', max_length=255)),
                ('phone', models.CharField(db_column='Phone', max_length=13)),
                ('tel_atcn_client', models.CharField(db_column='TelAtcnclient', max_length=13)),
                ('cell', models.CharField(db_column='Cell', max_length=13)),
                ('default_load_type', models.IntegerField(db_column='Defaultloadtype')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('idcountry', models.SmallAutoField(db_column='IdCountry', primary_key=True, serialize=False)),
                ('initials', models.CharField(db_column='Initials', max_length=3)),
                ('name', models.CharField(db_column='Name', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('iddocument_type', models.AutoField(db_column='IdDocumentType', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='IdTypeDocument', max_length=100)),
                ('description', models.TextField(db_column='Description')),
            ],
        ),
        migrations.CreateModel(
            name='TypeCompany',
            fields=[
                ('idtype_company', models.AutoField(db_column='IdTypeCompany', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('description', models.TextField(db_column='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('idprovince', models.AutoField(db_column='IdProvince', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('idcountry', models.ForeignKey(db_column='IdCountry', on_delete=django.db.models.deletion.CASCADE, to='company.country')),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('idlocation', models.AutoField(db_column='IdLocation', primary_key=True, serialize=False)),
                ('location', models.CharField(db_column='Location', max_length=250)),
                ('state', models.BooleanField(db_column='State', default=True)),
                ('idprovince', models.ForeignKey(db_column='IdProvince', on_delete=django.db.models.deletion.CASCADE, to='company.province')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalTypeCompany',
            fields=[
                ('idtype_company', models.IntegerField(blank=True, db_column='IdTypeCompany', db_index=True)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('description', models.TextField(db_column='Description')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical type company',
                'verbose_name_plural': 'historical type companys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProvince',
            fields=[
                ('idprovince', models.IntegerField(blank=True, db_column='IdProvince', db_index=True)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('idcountry', models.ForeignKey(blank=True, db_column='IdCountry', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.country')),
            ],
            options={
                'verbose_name': 'historical province',
                'verbose_name_plural': 'historical provinces',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLocality',
            fields=[
                ('idlocation', models.IntegerField(blank=True, db_column='IdLocation', db_index=True)),
                ('location', models.CharField(db_column='Location', max_length=250)),
                ('state', models.BooleanField(db_column='State', default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('idprovince', models.ForeignKey(blank=True, db_column='IdProvince', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.province')),
            ],
            options={
                'verbose_name': 'historical locality',
                'verbose_name_plural': 'historical localitys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDocumentType',
            fields=[
                ('iddocument_type', models.IntegerField(blank=True, db_column='IdDocumentType', db_index=True)),
                ('name', models.CharField(db_column='IdTypeDocument', max_length=100)),
                ('description', models.TextField(db_column='Description')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical document type',
                'verbose_name_plural': 'historical document types',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDocuments',
            fields=[
                ('iddocument', models.IntegerField(blank=True, db_column='IdDocument', db_index=True)),
                ('issue_date', models.DateField(db_column='IssueDate')),
                ('expiration_date', models.DateField(db_column='ExpirationDate')),
                ('attachment', models.TextField(blank=True, db_column='Attachment', max_length=255, null=True)),
                ('cost_procedure', models.DecimalField(db_column='CostProcedure', decimal_places=2, max_digits=10)),
                ('observations', models.CharField(db_column='Observations', max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('idcompany', models.ForeignKey(blank=True, db_column='IdCompany', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company')),
                ('idtype_document', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.documenttype')),
            ],
            options={
                'verbose_name': 'historical documents',
                'verbose_name_plural': 'historical documentss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCountry',
            fields=[
                ('idcountry', models.IntegerField(blank=True, db_column='IdCountry', db_index=True)),
                ('initials', models.CharField(db_column='Initials', max_length=3)),
                ('name', models.CharField(db_column='Name', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical country',
                'verbose_name_plural': 'historical countrys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCompany',
            fields=[
                ('idcompany', models.IntegerField(blank=True, db_column='IdCompany', db_index=True)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('logo', models.TextField(blank=True, db_column='Logo', max_length=255, null=True)),
                ('ruc', models.CharField(db_column='Ruc', max_length=13)),
                ('address', models.CharField(db_column='Address', max_length=255)),
                ('email', models.CharField(db_column='Email', max_length=255)),
                ('phone', models.CharField(db_column='Phone', max_length=13)),
                ('tel_atcn_client', models.CharField(db_column='TelAtcnclient', max_length=13)),
                ('cell', models.CharField(db_column='Cell', max_length=13)),
                ('default_load_type', models.IntegerField(db_column='Defaultloadtype')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('idlocation', models.ForeignKey(blank=True, db_column='IdLocation', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.locality')),
                ('idtype_company', models.ForeignKey(blank=True, db_column='IdTypeCompany', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.typecompany')),
            ],
            options={
                'verbose_name': 'historical company',
                'verbose_name_plural': 'historical companys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBankAccounts',
            fields=[
                ('idbank_account', models.IntegerField(blank=True, db_column='IdBankAccount', db_index=True)),
                ('bank_name', models.CharField(db_column='BankName', max_length=100)),
                ('account_number', models.CharField(db_column='AccountNumber', max_length=255)),
                ('default', models.BooleanField(db_column='Default ', default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('idcompany', models.ForeignKey(blank=True, db_column='IdCompany', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company')),
            ],
            options={
                'verbose_name': 'historical bank accounts',
                'verbose_name_plural': 'historical bank accountss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('iddocument', models.AutoField(db_column='IdDocument', primary_key=True, serialize=False)),
                ('issue_date', models.DateField(db_column='IssueDate')),
                ('expiration_date', models.DateField(db_column='ExpirationDate')),
                ('attachment', models.FileField(blank=True, db_column='Attachment', max_length=255, null=True, upload_to='document/company/')),
                ('cost_procedure', models.DecimalField(db_column='CostProcedure', decimal_places=2, max_digits=10)),
                ('observations', models.CharField(db_column='Observations', max_length=255)),
                ('idcompany', models.ForeignKey(db_column='IdCompany', on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('idtype_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.documenttype')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='idlocation',
            field=models.ForeignKey(db_column='IdLocation', on_delete=django.db.models.deletion.CASCADE, to='company.locality'),
        ),
        migrations.AddField(
            model_name='company',
            name='idtype_company',
            field=models.ForeignKey(db_column='IdTypeCompany', on_delete=django.db.models.deletion.CASCADE, to='company.typecompany'),
        ),
        migrations.CreateModel(
            name='BankAccounts',
            fields=[
                ('idbank_account', models.AutoField(db_column='IdBankAccount', primary_key=True, serialize=False)),
                ('bank_name', models.CharField(db_column='BankName', max_length=100)),
                ('account_number', models.CharField(db_column='AccountNumber', max_length=255)),
                ('default', models.BooleanField(db_column='Default ', default=False)),
                ('idcompany', models.ForeignKey(db_column='IdCompany', on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
