# Generated by Django 4.2.1 on 2023-06-06 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('iddocument_type', models.AutoField(db_column='IdDocumentType', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('description', models.TextField(db_column='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('idemployee', models.AutoField(db_column='IdEmployee', primary_key=True, serialize=False)),
                ('identificationcard', models.CharField(blank=True, db_column='IdentificationCard', max_length=10, null=True)),
                ('names', models.CharField(db_column='Names', max_length=100)),
                ('lastnames', models.CharField(db_column='Lastname', max_length=100)),
                ('birth_date', models.DateField(db_column='BirthDate')),
                ('photo', models.ImageField(blank=True, db_column='Photo', max_length=255, null=True, upload_to='photo/')),
                ('address', models.CharField(db_column='Address', max_length=255)),
                ('email', models.CharField(db_column='Email', max_length=255)),
                ('phone', models.CharField(db_column='Phone', max_length=255)),
                ('cell', models.CharField(db_column='Cell', max_length=255)),
                ('observations', models.CharField(db_column='Observations', max_length=255)),
                ('salary', models.DecimalField(db_column='Salary', decimal_places=2, max_digits=10)),
                ('entry_date', models.DateField(db_column='EntryDate')),
                ('idcompany', models.ForeignKey(db_column='IdCompany', on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('idlocation', models.ForeignKey(db_column='IdLocation', on_delete=django.db.models.deletion.CASCADE, to='company.locality')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodPayment',
            fields=[
                ('idperiod_payment', models.AutoField(db_column='IdPeriodPayment', primary_key=True, serialize=False)),
                ('period', models.CharField(db_column='Period', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PositionType',
            fields=[
                ('idposition_type', models.AutoField(db_column='IdPositionType', primary_key=True, serialize=False)),
                ('job_type_name', models.CharField(db_column='JobTypeName', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('idposition', models.AutoField(db_column='IdPosition', primary_key=True, serialize=False)),
                ('job_name', models.CharField(db_column='JobName', max_length=255)),
                ('idposition_type', models.ForeignKey(db_column='IdPositionType', on_delete=django.db.models.deletion.CASCADE, to='employees.positiontype')),
            ],
        ),
        migrations.CreateModel(
            name='LaborPayments',
            fields=[
                ('idlabor_payments', models.AutoField(db_column='IdLaborPayments', primary_key=True, serialize=False)),
                ('payment_type', models.CharField(db_column='PaymentType', max_length=255)),
                ('calculation', models.CharField(db_column='Calculation', max_length=255)),
                ('affects', models.CharField(db_column='Affects', max_length=255)),
                ('idemployee', models.ForeignKey(db_column='IdEmployee', on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='IsLogin',
            fields=[
                ('idislogin', models.AutoField(db_column='IdIsLogin', primary_key=True, serialize=False)),
                ('islogin', models.BooleanField(db_column='IsLogin', default=False)),
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idemployee', models.OneToOneField(db_column='IdEmployee', on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPositionType',
            fields=[
                ('idposition_type', models.IntegerField(blank=True, db_column='IdPositionType', db_index=True)),
                ('job_type_name', models.CharField(db_column='JobTypeName', max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical position type',
                'verbose_name_plural': 'historical position types',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPosition',
            fields=[
                ('idposition', models.IntegerField(blank=True, db_column='IdPosition', db_index=True)),
                ('job_name', models.CharField(db_column='JobName', max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('idposition_type', models.ForeignKey(blank=True, db_column='IdPositionType', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.positiontype')),
            ],
            options={
                'verbose_name': 'historical position',
                'verbose_name_plural': 'historical positions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPeriodPayment',
            fields=[
                ('idperiod_payment', models.IntegerField(blank=True, db_column='IdPeriodPayment', db_index=True)),
                ('period', models.CharField(db_column='Period', max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical period payment',
                'verbose_name_plural': 'historical period payments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLaborPayments',
            fields=[
                ('idlabor_payments', models.IntegerField(blank=True, db_column='IdLaborPayments', db_index=True)),
                ('payment_type', models.CharField(db_column='PaymentType', max_length=255)),
                ('calculation', models.CharField(db_column='Calculation', max_length=255)),
                ('affects', models.CharField(db_column='Affects', max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('idemployee', models.ForeignKey(blank=True, db_column='IdEmployee', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.employee')),
            ],
            options={
                'verbose_name': 'historical labor payments',
                'verbose_name_plural': 'historical labor paymentss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalIsLogin',
            fields=[
                ('idislogin', models.IntegerField(blank=True, db_column='IdIsLogin', db_index=True)),
                ('islogin', models.BooleanField(db_column='IsLogin', default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id', models.ForeignKey(blank=True, db_column='id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('idemployee', models.ForeignKey(blank=True, db_column='IdEmployee', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.employee')),
            ],
            options={
                'verbose_name': 'historical is login',
                'verbose_name_plural': 'historical is logins',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEmployee',
            fields=[
                ('idemployee', models.IntegerField(blank=True, db_column='IdEmployee', db_index=True)),
                ('identificationcard', models.CharField(blank=True, db_column='IdentificationCard', max_length=10, null=True)),
                ('names', models.CharField(db_column='Names', max_length=100)),
                ('lastnames', models.CharField(db_column='Lastname', max_length=100)),
                ('birth_date', models.DateField(db_column='BirthDate')),
                ('photo', models.TextField(blank=True, db_column='Photo', max_length=255, null=True)),
                ('address', models.CharField(db_column='Address', max_length=255)),
                ('email', models.CharField(db_column='Email', max_length=255)),
                ('phone', models.CharField(db_column='Phone', max_length=255)),
                ('cell', models.CharField(db_column='Cell', max_length=255)),
                ('observations', models.CharField(db_column='Observations', max_length=255)),
                ('salary', models.DecimalField(db_column='Salary', decimal_places=2, max_digits=10)),
                ('entry_date', models.DateField(db_column='EntryDate')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('idcompany', models.ForeignKey(blank=True, db_column='IdCompany', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company')),
                ('idlocation', models.ForeignKey(blank=True, db_column='IdLocation', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.locality')),
                ('idperiod_payment', models.ForeignKey(blank=True, db_column='IdPeriodPayment', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.periodpayment')),
                ('idposition', models.ForeignKey(blank=True, db_column='IdPosition', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.position')),
            ],
            options={
                'verbose_name': 'historical employee',
                'verbose_name_plural': 'historical employees',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDocumentType',
            fields=[
                ('iddocument_type', models.IntegerField(blank=True, db_column='IdDocumentType', db_index=True)),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('description', models.TextField(db_column='Description')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical document type',
                'verbose_name_plural': 'historical document types',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDocumentEmployee',
            fields=[
                ('iddocument_employee', models.IntegerField(blank=True, db_column='IdDocumentEmployee', db_index=True)),
                ('issue_date', models.DateField(db_column='Issue_Date')),
                ('expiration_date', models.DateField(db_column='Expiration_Date')),
                ('attachment', models.TextField(blank=True, db_column='Attachment', max_length=255, null=True)),
                ('procedure_cost', models.DecimalField(db_column='ProcedureCosto', decimal_places=2, max_digits=10)),
                ('observations', models.CharField(db_column='Observations', max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('iddocument_type', models.ForeignKey(blank=True, db_column='IdDocumentType', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.documenttype')),
                ('idemployee', models.ForeignKey(blank=True, db_column='IdEmployee', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.employee')),
            ],
            options={
                'verbose_name': 'historical document employee',
                'verbose_name_plural': 'historical document employees',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='employee',
            name='idperiod_payment',
            field=models.ForeignKey(db_column='IdPeriodPayment', on_delete=django.db.models.deletion.CASCADE, to='employees.periodpayment'),
        ),
        migrations.AddField(
            model_name='employee',
            name='idposition',
            field=models.ForeignKey(db_column='IdPosition', on_delete=django.db.models.deletion.CASCADE, to='employees.position'),
        ),
        migrations.CreateModel(
            name='DocumentEmployee',
            fields=[
                ('iddocument_employee', models.AutoField(db_column='IdDocumentEmployee', primary_key=True, serialize=False)),
                ('issue_date', models.DateField(db_column='Issue_Date')),
                ('expiration_date', models.DateField(db_column='Expiration_Date')),
                ('attachment', models.FileField(blank=True, db_column='Attachment', max_length=255, null=True, upload_to='document/employee/')),
                ('procedure_cost', models.DecimalField(db_column='ProcedureCosto', decimal_places=2, max_digits=10)),
                ('observations', models.CharField(db_column='Observations', max_length=255)),
                ('iddocument_type', models.ForeignKey(db_column='IdDocumentType', on_delete=django.db.models.deletion.CASCADE, to='employees.documenttype')),
                ('idemployee', models.ForeignKey(db_column='IdEmployee', on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
    ]
